---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    operations: monitoring-dashboard
spec:
  selector:
    app: grafana-deployment
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000

---

# Persist the Grafana data

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

# This pod is separated from the scrapper and does not
#   have any critical role, nor expected frequently updates,
#   so it is fine to use a pod.
apiVersion: v1
kind: Pod
metadata:
  name: grafana-deployment
  labels:
    app: grafana
    operations: monitoring-dashboard
spec:
  containers:
    - image: grafana/grafana
      imagePullPolicy: Always
      name: grafana-deployment-dashboard
      ports:
        - containerPort: 3000
          protocol: TCP
      resources:
        requests:
          cpu: 100m
      volumeMounts:
        - name: grafana-persistent-storage
          mountPath: /var/lib/grafana
  securityContext:
    fsGroup: 472
  volumes:
    - name: grafana-persistent-storage
      persistentVolumeClaim:
        claimName: grafana-data


---

kind: Service
apiVersion: v1
metadata:
  name: prometheus-service
  labels:
    app: prometheus
    operations: target-scrapper
spec:
  selector:
    app: prometheus-deployment
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 9090

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    operations: target-scrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      operations: target-scrapper
  template:
    metadata:
      labels:
        operations: target-scrapper
    spec:
      containers:
        - image: prom/prometheus
          imagePullPolicy: Always
          name: prometheus
          ports:
            - containerPort: 9090
              protocol: TCP
          resources:
            requests:
              cpu: 100m
